const templates = [
  {
    name: "Gym Template",
    key: "wally-membership",
    description: "Wally Membership",
    image: "/images/loyalty/templates/wally-fit.png",
    type: "membership",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      stampIcon: '',
      unStampIcon: '',
      stampImage: "",
      stampImageColor: "",
      unStampImage: "",
      unStampImageColor: "",
      rectangleBehindStamps: "",
      backgroundImage: "",
      stampsNumber: "10",
      circle: "",
      circleBorder: "",
      background: "#ffffff",
      text: "#000000",
      stampImagePreview: "",
      stripImagePreviewApple: "/images/loyalty/templates/wally-apple-strip-gym.png",
      stripImagePreviewGoogle: "/images/loyalty/templates/wally-apple-strip-gym.png",
      // appleLogo: "/images/loyalty/templates/wally-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/wally-google-logo.png",
      // appleStrip: "/images/loyalty/templates/wally-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/wally-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
      },
    },
    additionalFields: [
      {
        title: "Terms",
        description: "Please fill in your Terms and Condition",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free coffee after 10 stamps",
      howToEarn: "Earn a stamp for every coffee you buy",
      businessName: "Coffee Shop",
      rewardDetails: "Free coffee",
      description: "Please fill in your Reward Details",
      stampSuccessMessage: "{#} more stamps until your free coffee!",
      rewardSuccessMessage: "{#} more stamps until your free coffee!",
      locations: [],
      usefulLinks: [
        {
          text: "Follow us on twitter",
          link: "http://twitter.com",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Balance Template",
    key: "wally-balance",
    description: "Balance Top-Up Card",
    image: "/images/loyalty/templates/balance-topup.png",
    type: "balance",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      stampIcon: '',
      unStampIcon: '',
      stampImage: "",
      stampImageColor: "",
      unStampImage: "",
      unStampImageColor: "",
      rectangleBehindStamps: "",
      backgroundImage: "",
      stampsNumber: "10",
      circle: "",
      circleBorder: "",
      background: "#ffffff",
      text: "#000000",
      stampImagePreview: "",
      stripImagePreviewApple: "/images/loyalty/templates/wally-apple-strip-gym.png",
      stripImagePreviewGoogle: "/images/loyalty/templates/wally-apple-strip-gym.png",
      // appleLogo: "/images/loyalty/templates/wally-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/wally-google-logo.png",
      // appleStrip: "/images/loyalty/templates/wally-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/wally-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
        f5: "empty",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
        f5: "empty",
      },
    },
    additionalFields: [
      {
        title: "Terms",
        description: "Please fill in your Terms and Condition",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Top up your balance and get exclusive rewards.",
      howToEarn: "Add funds to your balance to receive loyalty bonuses.",
      businessName: "Wally Balance",
      rewardDetails: "Receive a 5% bonus on each top-up over $50.",
      description: "Top up your card and enjoy exclusive rewards on every balance addition.",
      topUpSuccessMessage: "Successfully topped up! Your new balance is {#}.",
      rewardSuccessMessage: "Earn extra rewards on your next top-up.",
      locations: [
        { name: "Wally Fitness Center", address: "123 Fitness St., Downtown Dubai" },
        { name: "Wally Café", address: "456 Café Ave., Amsterdam" },
      ],
      usefulLinks: [
        {
          text: "Check Balance",
          link: "http://wally-balance.com/check",
          type: "Url",
        },
        {
          text: "Top-Up Online",
          link: "http://wally-balance.com/top-up",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Stamp Template",
    key: "wally",
    description: "Wally Stamp",
    image: "/images/loyalty/templates/wally-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      stampIcon: 'baguette',
      unStampIcon: 'baguette',
      stampImage: "baguette",
      stampImageColor: "#000000",
      unStampImage: "baguette",
      unStampImageColor: " #333333",
      rectangleBehindStamps: "#ffffff",
      backgroundImage: "",
      stampsNumber: 10,
      circle: "#ffffff",
      circleBorder: "#000000",
      background: "#ffffff",
      text: "#000000",
      stampImagePreview: "/images/loyalty/templates/wally-apple-strip.png",
      // appleLogo: "/images/loyalty/templates/wally-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/wally-google-logo.png",
      // appleStrip: "/images/loyalty/templates/wally-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/wally-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Reward your customers with a free item or a discount",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Please fill in your Terms and Condition",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free coffee after 10 stamps",
      howToEarn: "Earn a stamp for every coffee you buy",
      businessName: "Coffee Shop",
      rewardDetails: "Free coffee",
      description: "Please fill in your Reward Details",
      stampSuccessMessage: "{#} more stamps until your free coffee!",
      rewardSuccessMessage: "{#} more stamps until your free coffee!",
      locations: [],
      usefulLinks: [
        {
          text: "Follow us on twitter",
          link: "http://twitter.com",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Wally",
    key: "wally",
    description: "Wally template",
    image: "/images/loyalty/templates/wally-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      stampIcon: '',
      unStampIcon: '',
      stampImage: "",
      stampImageColor: "",
      unStampImage: "",
      unStampImageColor: "",
      rectangleBehindStamps: "",
      backgroundImage: "",
      stampsNumber: "10",
      circle: "",
      circleBorder: "",
      background: "#ffffff",
      text: "#000000",
      stampImagePreview: "/images/loyalty/templates/wally-apple-strip.png",
      // appleLogo: "/images/loyalty/templates/wally-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/wally-google-logo.png",
      // appleStrip: "/images/loyalty/templates/wally-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/wally-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Reward your customers with a free item or a discount",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Please fill in your Terms and Condition",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free coffee after 10 stamps",
      howToEarn: "Earn a stamp for every coffee you buy",
      businessName: "Coffee Shop",
      rewardDetails: "Free coffee",
      description: "Please fill in your Reward Details",
      stampSuccessMessage: "{#} more stamps until your free coffee!",
      rewardSuccessMessage: "{#} more stamps until your free coffee!",
      locations: [],
      usefulLinks: [
        {
          text: "Follow us on twitter",
          link: "http://twitter.com",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Clean",
    key: "clean",
    description: "Clean template",
    image: "/images/loyalty/templates/clean-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      background: "#ffffff",
      text: "#000000",
      // appleLogo: "/images/loyalty/templates/clean-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/clean-google-logo.png",
      // appleStrip: "/images/loyalty/templates/clean-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/clean-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Reward your customers with a special discount or item",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Enter your Terms and Conditions",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get rewarded after 10 purchases",
      howToEarn: "Earn rewards by making purchases",
      businessName: "Your Business",
      rewardDetails: "10% off on your next purchase",
      description: "Please provide Reward details",
      stampSuccessMessage: "{#} more purchases for a reward!",
      rewardSuccessMessage: "{#} more purchases for your reward!",
      locations: [],
      usefulLinks: [
        {
          text: "Check out our Facebook",
          link: "http://facebook.com",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Barber Shop",
    key: "barbershop",
    description: "Barber Shop template",
    image: "/images/loyalty/templates/barbershop-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      background: "#222222",
      text: "#ffffff",
      // appleLogo: "/images/loyalty/templates/barbershop-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/barbershop-google-logo.png",
      // appleStrip: "/images/loyalty/templates/barbershop-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/barbershop-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Offer a discount or a free service to loyal customers",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Please enter your Terms and Conditions",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free haircut after 5 visits",
      howToEarn: "Earn a stamp for every visit",
      businessName: "Barber Shop",
      rewardDetails: "Free haircut",
      description: "Fill in Reward details here",
      stampSuccessMessage: "{#} more visits until your free haircut!",
      rewardSuccessMessage: "{#} more visits for your reward!",
      locations: [],
      usefulLinks: [
        {
          text: "Follow us on Instagram",
          link: "http://instagram.com",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Beauty Salon",
    key: "beauty-salon",
    description: "Beauty Salon template",
    image: "/images/loyalty/templates/beauty-salon-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      background: "#412A66",
      text: "#ffffff",
      // appleLogo: "/images/loyalty/templates/beauty-salon-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/beauty-salon-google-logo.png",
      // appleStrip: "/images/loyalty/templates/beauty-salon-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/beauty-salon-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Offer beauty service discounts or free treatments",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Please add Terms and Conditions",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free treatment after 5 visits",
      howToEarn: "Earn a stamp for each beauty treatment",
      businessName: "Beauty Salon",
      rewardDetails: "Free beauty treatment",
      description: "Fill in Reward details",
      stampSuccessMessage: "{#} more visits until your free treatment!",
      rewardSuccessMessage: "{#} more visits for your reward!",
      locations: [],
      usefulLinks: [
        {
          text: "Find us on Instagram",
          link: "http://instagram.com",
          type: "Url",
        },
      ],
    },
  },

  {
    name: "Eye Brow",
    key: "eyebrow",
    description: "Eye Brow template",
    image: "/images/loyalty/templates/eyebrow-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      background: "#efeff1",
      text: "#000000",
      // appleLogo: "/images/loyalty/templates/eyebrow-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/eyebrow-google-logo.png",
      // appleStrip: "/images/loyalty/templates/eyebrow-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/eyebrow-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Offer discounts on eyebrow services or free services",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Please provide Terms and Conditions",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free eyebrow service after 5 visits",
      howToEarn: "Earn a stamp for every eyebrow service",
      businessName: "Eyebrow Salon",
      rewardDetails: "Free eyebrow shaping",
      description: "Fill in Reward details here",
      stampSuccessMessage: "{#} more visits until your free service!",
      rewardSuccessMessage: "{#} more visits for your reward!",
      locations: [],
      usefulLinks: [
        {
          text: "Follow us on Pinterest",
          link: "http://pinterest.com",
          type: "Url",
        },
      ],
    },
  },
  {
    name: "Nail Salon",
    key: "nail",
    description: "Nail Salon template",
    image: "/images/loyalty/templates/nail-prw.png",
    type: "stamp",
    properties: {
      icon: "/images/loyalty/templates/wally-google-logo.png",
      logo: "/images/loyalty/templates/wally-apple-logo.png",
      reward:'/images/loyalty/templates/reward.jpg',
      background: "#10026A",
      text: "#000000",
      // appleLogo: "/images/loyalty/templates/nail-apple-logo.png",
      // googleLogo: "/images/loyalty/templates/nail-google-logo.png",
      // appleStrip: "/images/loyalty/templates/nail-apple-strip.png",
      // googleStrip: "/images/loyalty/templates/nail-google-strip.png",
    },
    fields: {
      apple: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
        f5: "empty",
      },
      google: {
        f1: "name",
        f2: "phone",
        f3: "email",
        f4: "stampCount",
        f5: "empty",
      },
    },
    additionalFields: [
      {
        title: "Reward",
        description: "Provide discounts on nail services or free treatments",
        type: "Text",
      },
      {
        title: "Terms",
        description: "Add your Terms and Conditions here",
        type: "Text",
      },
    ],
    enrollmentForm: {
      fields: [],
      design: {},
    },
    details: {
      cardDescription: "Get a free nail polish change after 5 visits",
      howToEarn: "Earn a stamp for every nail service",
      businessName: "Nail Salon",
      rewardDetails: "Free nail service",
      description: "Fill in Reward details here",
      stampSuccessMessage: "{#} more visits until your free nail service!",
      rewardSuccessMessage: "{#} more visits for your reward!",
      locations: [],
      usefulLinks: [
        {
          text: "Check out our YouTube channel",
          link: "http://youtube.com",
          type: "Url",
        },
      ],
    },
  },
];

const currencies = [
  { symbol: "USD", name: "$ - US Dollar" },
  { symbol: "EUR", name: "€ - Euro" },
  { symbol: "JPY", name: "¥ - Japanese Yen" },
  { symbol: "GBP", name: "£ - British Pound" },
  { symbol: "AUD", name: "A$ - Australian Dollar" },
  { symbol: "CAD", name: "C$ - Canadian Dollar" },
  { symbol: "CHF", name: "CHF - Swiss Franc" },
  { symbol: "CNY", name: "¥ - Chinese Yuan" },
  { symbol: "SEK", name: "kr - Swedish Krona" },
  { symbol: "NZD", name: "NZ$ - New Zealand Dollar" },
  { symbol: "MXN", name: "$ - Mexican Peso" },
  { symbol: "SGD", name: "S$ - Singapore Dollar" },
  { symbol: "HKD", name: "HK$ - Hong Kong Dollar" },
  { symbol: "NOK", name: "kr - Norwegian Krone" },
  { symbol: "KRW", name: "₩ - South Korean Won" },
  { symbol: "TRY", name: "₺ - Turkish Lira" },
  { symbol: "INR", name: "₹ - Indian Rupee" },
  { symbol: "RUB", name: "₽ - Russian Ruble" },
  { symbol: "BRL", name: "R$ - Brazilian Real" },
  { symbol: "ZAR", name: "R - South African Rand" },
  { symbol: "PHP", name: "₱ - Philippine Peso" },
  { symbol: "CZK", name: "Kč - Czech Koruna" },
  { symbol: "PLN", name: "zł - Polish Zloty" },
  { symbol: "DKK", name: "kr - Danish Krone" },
  { symbol: "HUF", name: "Ft - Hungarian Forint" },
  { symbol: "MYR", name: "RM - Malaysian Ringgit" },
  { symbol: "THB", name: "฿ - Thai Baht" },
  { symbol: "IDR", name: "Rp - Indonesian Rupiah" },
  { symbol: "ILS", name: "₪ - Israeli Shekel" },
  { symbol: "CLP", name: "$ - Chilean Peso" },
  { symbol: "PKR", name: "₨ - Pakistani Rupee" },
  { symbol: "AED", name: "د.إ - UAE Dirham" },
  { symbol: "SAR", name: "﷼ - Saudi Riyal" },
  { symbol: "NGN", name: "₦ - Nigerian Naira" },
  { symbol: "COP", name: "$ - Colombian Peso" },
  { symbol: "EGP", name: "£ - Egyptian Pound" },
  { symbol: "VND", name: "₫ - Vietnamese Dong" },
  { symbol: "BDT", name: "৳ - Bangladeshi Taka" },
  { symbol: "KWD", name: "د.ك - Kuwaiti Dinar" },
  { symbol: "GHS", name: "₵ - Ghanaian Cedi" },
  { symbol: "MAD", name: "د.م. - Moroccan Dirham" },
  { symbol: "QAR", name: "﷼ - Qatari Riyal" },
  { symbol: "OMR", name: "﷼ - Omani Rial" },
  { symbol: "LKR", name: "₨ - Sri Lankan Rupee" },
  { symbol: "KHR", name: "៛ - Cambodian Riel" },
  { symbol: "KES", name: "KSh - Kenyan Shilling" },
  { symbol: "TZS", name: "TSh - Tanzanian Shilling" },
  { symbol: "UGX", name: "USh - Ugandan Shilling" },
  { symbol: "MMK", name: "K - Myanmar Kyat" },
  { symbol: "NPR", name: "₨ - Nepalese Rupee" },
  { symbol: "BHD", name: "BD - Bahraini Dinar" },
  { symbol: "JOD", name: "JD - Jordanian Dinar" },
  { symbol: "LAK", name: "₭ - Lao Kip" },
  { symbol: "MOP", name: "MOP$ - Macanese Pataca" },
  { symbol: "SYP", name: "£S - Syrian Pound" }
];


const fields = [
  { name: "Name", label: "Name", key: "name", sample: "John Doe", requiredOnEnrollment: true, type: "text" },
  { name: "Phone", label: "Phone", key: "phone", sample: "1234567890", requiredOnEnrollment: true, type: "text" },
  { name: "Email", label: "Email", key: "email", sample: "user@domain.com", requiredOnEnrollment: true, type: "email" },
  { name: "Empty", label: "", key: "empty", sample: "", requiredOnEnrollment: false, type: "empty" },
  {
    name: "Birthday",
    label: "Birthday",
    key: "birthday",
    sample: "01/01/2000",
    requiredOnEnrollment: true,
    type: "date",
  },
  { name: "Gender", label: "Gender", key: "gender", sample: "Male", requiredOnEnrollment: true, type: "text" },
  { name: "Age", label: "Age", key: "age", sample: "21", requiredOnEnrollment: true, type: "number" },
  {
    name: "Customer ID",
    label: "Customer ID",
    key: "customerId",
    sample: "#1234567",
    requiredOnEnrollment: false,
  },
  {
    name: "Stamp Count",
    label: "Stamp Count",
    key: "stampCount",
    sample: "5",
    requiredOnEnrollment: false,
  },
  {
    name: "Balance",
    label: "Top-up Balance",
    key: "balance",
    requiredOnEnrollment: false,
  },
  { name: "Currency", label: "currency", key: "currency", requiredOnEnrollment: false },
  
];

const textColors = [
  "text-red",
  "text-red-lighten-5",
  "text-red-lighten-4",
  "text-red-lighten-3",
  "text-red-lighten-2",
  "text-red-lighten-1",
  "text-red-darken-1",
  "text-red-darken-2",
  "text-red-darken-3",
  "text-red-darken-4",
  "text-red-accent-1",
  "text-red-accent-2",
  "text-red-accent-3",
  "text-red-accent-4",
  "text-pink",
  "text-pink-lighten-5",
  "text-pink-lighten-4",
  "text-pink-lighten-3",
  "text-pink-lighten-2",
  "text-pink-lighten-1",
  "text-pink-darken-1",
  "text-pink-darken-2",
  "text-pink-darken-3",
  "text-pink-darken-4",
  "text-pink-accent-1",
  "text-pink-accent-2",
  "text-pink-accent-3",
  "text-pink-accent-4",
  "text-purple",
  "text-purple-lighten-5",
  "text-purple-lighten-4",
  "text-purple-lighten-3",
  "text-purple-lighten-2",
  "text-purple-lighten-1",
  "text-purple-darken-1",
  "text-purple-darken-2",
  "text-purple-darken-3",
  "text-purple-darken-4",
  "text-purple-accent-1",
  "text-purple-accent-2",
  "text-purple-accent-3",
  "text-purple-accent-4",
  "text-deep-purple",
  "text-deep-purple-lighten-5",
  "text-deep-purple-lighten-4",
  "text-deep-purple-lighten-3",
  "text-deep-purple-lighten-2",
  "text-deep-purple-lighten-1",
  "text-deep-purple-darken-1",
  "text-deep-purple-darken-2",
  "text-deep-purple-darken-3",
  "text-deep-purple-darken-4",
  "text-deep-purple-accent-1",
  "text-deep-purple-accent-2",
  "text-deep-purple-accent-3",
  "text-deep-purple-accent-4",
  "text-indigo",
  "text-indigo-lighten-5",
  "text-indigo-lighten-4",
  "text-indigo-lighten-3",
  "text-indigo-lighten-2",
  "text-indigo-lighten-1",
  "text-indigo-darken-1",
  "text-indigo-darken-2",
  "text-indigo-darken-3",
  "text-indigo-darken-4",
  "text-indigo-accent-1",
  "text-indigo-accent-2",
  "text-indigo-accent-3",
  "text-indigo-accent-4",
  "text-blue",
  "text-blue-lighten-5",
  "text-blue-lighten-4",
  "text-blue-lighten-3",
  "text-blue-lighten-2",
  "text-blue-lighten-1",
  "text-blue-darken-1",
  "text-blue-darken-2",
  "text-blue-darken-3",
  "text-blue-darken-4",
  "text-blue-accent-1",
  "text-blue-accent-2",
  "text-blue-accent-3",
  "text-blue-accent-4",
  "text-light-blue",
  "text-light-blue-lighten-5",
  "text-light-blue-lighten-4",
  "text-light-blue-lighten-3",
  "text-light-blue-lighten-2",
  "text-light-blue-lighten-1",
  "text-light-blue-darken-1",
  "text-light-blue-darken-2",
  "text-light-blue-darken-3",
  "text-light-blue-darken-4",
  "text-light-blue-accent-1",
  "text-light-blue-accent-2",
  "text-light-blue-accent-3",
  "text-light-blue-accent-4",
  "text-cyan",
  "text-cyan-lighten-5",
  "text-cyan-lighten-4",
  "text-cyan-lighten-3",
  "text-cyan-lighten-2",
  "text-cyan-lighten-1",
  "text-cyan-darken-1",
  "text-cyan-darken-2",
  "text-cyan-darken-3",
  "text-cyan-darken-4",
  "text-cyan-accent-1",
  "text-cyan-accent-2",
  "text-cyan-accent-3",
  "text-cyan-accent-4",
  "text-teal",
  "text-teal-lighten-5",
  "text-teal-lighten-4",
  "text-teal-lighten-3",
  "text-teal-lighten-2",
  "text-teal-lighten-1",
  "text-teal-darken-1",
  "text-teal-darken-2",
  "text-teal-darken-3",
  "text-teal-darken-4",
  "text-teal-accent-1",
  "text-teal-accent-2",
  "text-teal-accent-3",
  "text-teal-accent-4",
  "text-green",
  "text-green-lighten-5",
  "text-green-lighten-4",
  "text-green-lighten-3",
  "text-green-lighten-2",
  "text-green-lighten-1",
  "text-green-darken-1",
  "text-green-darken-2",
  "text-green-darken-3",
  "text-green-darken-4",
  "text-green-accent-1",
  "text-green-accent-2",
  "text-green-accent-3",
  "text-green-accent-4",
  "text-light-green",
  "text-light-green-lighten-5",
  "text-light-green-lighten-4",
  "text-light-green-lighten-3",
  "text-light-green-lighten-2",
  "text-light-green-lighten-1",
  "text-light-green-darken-1",
  "text-light-green-darken-2",
  "text-light-green-darken-3",
  "text-light-green-darken-4",
  "text-light-green-accent-1",
  "text-light-green-accent-2",
  "text-light-green-accent-3",
  "text-light-green-accent-4",
  "text-lime",
  "text-lime-lighten-5",
  "text-lime-lighten-4",
  "text-lime-lighten-3",
  "text-lime-lighten-2",
  "text-lime-lighten-1",
  "text-lime-darken-1",
  "text-lime-darken-2",
  "text-lime-darken-3",
  "text-lime-darken-4",
  "text-lime-accent-1",
  "text-lime-accent-2",
  "text-lime-accent-3",
  "text-lime-accent-4",
  "text-yellow",
  "text-yellow-lighten-5",
  "text-yellow-lighten-4",
  "text-yellow-lighten-3",
  "text-yellow-lighten-2",
  "text-yellow-lighten-1",
  "text-yellow-darken-1",
  "text-yellow-darken-2",
  "text-yellow-darken-3",
  "text-yellow-darken-4",
  "text-yellow-accent-1",
  "text-yellow-accent-2",
  "text-yellow-accent-3",
  "text-yellow-accent-4",
  "text-amber",
  "text-amber-lighten-5",
  "text-amber-lighten-4",
  "text-amber-lighten-3",
  "text-amber-lighten-2",
  "text-amber-lighten-1",
  "text-amber-darken-1",
  "text-amber-darken-2",
  "text-amber-darken-3",
  "text-amber-darken-4",
  "text-amber-accent-1",
  "text-amber-accent-2",
  "text-amber-accent-3",
  "text-amber-accent-4",
  "text-orange",
  "text-orange-lighten-5",
  "text-orange-lighten-4",
  "text-orange-lighten-3",
  "text-orange-lighten-2",
  "text-orange-lighten-1",
  "text-orange-darken-1",
  "text-orange-darken-2",
  "text-orange-darken-3",
  "text-orange-darken-4",
  "text-orange-accent-1",
  "text-orange-accent-2",
  "text-orange-accent-3",
  "text-orange-accent-4",
  "text-deep-orange",
  "text-deep-orange-lighten-5",
  "text-deep-orange-lighten-4",
  "text-deep-orange-lighten-3",
  "text-deep-orange-lighten-2",
  "text-deep-orange-lighten-1",
  "text-deep-orange-darken-1",
  "text-deep-orange-darken-2",
  "text-deep-orange-darken-3",
  "text-deep-orange-darken-4",
  "text-deep-orange-accent-1",
  "text-deep-orange-accent-2",
  "text-deep-orange-accent-3",
  "text-deep-orange-accent-4",
  "text-brown",
  "text-brown-lighten-5",
  "text-brown-lighten-4",
  "text-brown-lighten-3",
  "text-brown-lighten-2",
  "text-brown-lighten-1",
  "text-brown-darken-1",
  "text-brown-darken-2",
  "text-brown-darken-3",
  "text-brown-darken-4",
  "text-blue-grey",
  "text-blue-grey-lighten-5",
  "text-blue-grey-lighten-4",
  "text-blue-grey-lighten-3",
  "text-blue-grey-lighten-2",
  "text-blue-grey-lighten-1",
  "text-blue-grey-darken-1",
  "text-blue-grey-darken-2",
  "text-blue-grey-darken-3",
  "text-blue-grey-darken-4",
];

const backgroundColors = [
  "bg-red",
  "bg-red-lighten-5",
  "bg-red-lighten-4",
  "bg-red-lighten-3",
  "bg-red-lighten-2",
  "bg-red-lighten-1",
  "bg-red-darken-1",
  "bg-red-darken-2",
  "bg-red-darken-3",
  "bg-red-darken-4",
  "bg-red-accent-1",
  "bg-red-accent-2",
  "bg-red-accent-3",
  "bg-red-accent-4",
  "bg-pink",
  "bg-pink-lighten-5",
  "bg-pink-lighten-4",
  "bg-pink-lighten-3",
  "bg-pink-lighten-2",
  "bg-pink-lighten-1",
  "bg-pink-darken-1",
  "bg-pink-darken-2",
  "bg-pink-darken-3",
  "bg-pink-darken-4",
  "bg-pink-accent-1",
  "bg-pink-accent-2",
  "bg-pink-accent-3",
  "bg-pink-accent-4",
  "bg-purple",
  "bg-purple-lighten-5",
  "bg-purple-lighten-4",
  "bg-purple-lighten-3",
  "bg-purple-lighten-2",
  "bg-purple-lighten-1",
  "bg-purple-darken-1",
  "bg-purple-darken-2",
  "bg-purple-darken-3",
  "bg-purple-darken-4",
  "bg-purple-accent-1",
  "bg-purple-accent-2",
  "bg-purple-accent-3",
  "bg-purple-accent-4",
  "bg-deep-purple",
  "bg-deep-purple-lighten-5",
  "bg-deep-purple-lighten-4",
  "bg-deep-purple-lighten-3",
  "bg-deep-purple-lighten-2",
  "bg-deep-purple-lighten-1",
  "bg-deep-purple-darken-1",
  "bg-deep-purple-darken-2",
  "bg-deep-purple-darken-3",
  "bg-deep-purple-darken-4",
  "bg-deep-purple-accent-1",
  "bg-deep-purple-accent-2",
  "bg-deep-purple-accent-3",
  "bg-deep-purple-accent-4",
  "bg-indigo",
  "bg-indigo-lighten-5",
  "bg-indigo-lighten-4",
  "bg-indigo-lighten-3",
  "bg-indigo-lighten-2",
  "bg-indigo-lighten-1",
  "bg-indigo-darken-1",
  "bg-indigo-darken-2",
  "bg-indigo-darken-3",
  "bg-indigo-darken-4",
  "bg-indigo-accent-1",
  "bg-indigo-accent-2",
  "bg-indigo-accent-3",
  "bg-indigo-accent-4",
  "bg-blue",
  "bg-blue-lighten-5",
  "bg-blue-lighten-4",
  "bg-blue-lighten-3",
  "bg-blue-lighten-2",
  "bg-blue-lighten-1",
  "bg-blue-darken-1",
  "bg-blue-darken-2",
  "bg-blue-darken-3",
  "bg-blue-darken-4",
  "bg-blue-accent-1",
  "bg-blue-accent-2",
  "bg-blue-accent-3",
  "bg-blue-accent-4",
  "bg-light-blue",
  "bg-light-blue-lighten-5",
  "bg-light-blue-lighten-4",
  "bg-light-blue-lighten-3",
  "bg-light-blue-lighten-2",
  "bg-light-blue-lighten-1",
  "bg-light-blue-darken-1",
  "bg-light-blue-darken-2",
  "bg-light-blue-darken-3",
  "bg-light-blue-darken-4",
  "bg-light-blue-accent-1",
  "bg-light-blue-accent-2",
  "bg-light-blue-accent-3",
  "bg-light-blue-accent-4",
  "bg-cyan",
  "bg-cyan-lighten-5",
  "bg-cyan-lighten-4",
  "bg-cyan-lighten-3",
  "bg-cyan-lighten-2",
  "bg-cyan-lighten-1",
  "bg-cyan-darken-1",
  "bg-cyan-darken-2",
  "bg-cyan-darken-3",
  "bg-cyan-darken-4",
  "bg-cyan-accent-1",
  "bg-cyan-accent-2",
  "bg-cyan-accent-3",
  "bg-cyan-accent-4",
  "bg-teal",
  "bg-teal-lighten-5",
  "bg-teal-lighten-4",
  "bg-teal-lighten-3",
  "bg-teal-lighten-2",
  "bg-teal-lighten-1",
  "bg-teal-darken-1",
  "bg-teal-darken-2",
  "bg-teal-darken-3",
  "bg-teal-darken-4",
  "bg-teal-accent-1",
  "bg-teal-accent-2",
  "bg-teal-accent-3",
  "bg-teal-accent-4",
  "bg-green",
  "bg-green-lighten-5",
  "bg-green-lighten-4",
  "bg-green-lighten-3",
  "bg-green-lighten-2",
  "bg-green-lighten-1",
  "bg-green-darken-1",
  "bg-green-darken-2",
  "bg-green-darken-3",
  "bg-green-darken-4",
  "bg-green-accent-1",
  "bg-green-accent-2",
  "bg-green-accent-3",
  "bg-green-accent-4",
  "bg-light-green",
  "bg-light-green-lighten-5",
  "bg-light-green-lighten-4",
  "bg-light-green-lighten-3",
  "bg-light-green-lighten-2",
  "bg-light-green-lighten-1",
  "bg-light-green-darken-1",
  "bg-light-green-darken-2",
  "bg-light-green-darken-3",
  "bg-light-green-darken-4",
  "bg-light-green-accent-1",
  "bg-light-green-accent-2",
  "bg-light-green-accent-3",
  "bg-light-green-accent-4",
  "bg-lime",
  "bg-lime-lighten-5",
  "bg-lime-lighten-4",
  "bg-lime-lighten-3",
  "bg-lime-lighten-2",
  "bg-lime-lighten-1",
  "bg-lime-darken-1",
  "bg-lime-darken-2",
  "bg-lime-darken-3",
  "bg-lime-darken-4",
  "bg-lime-accent-1",
  "bg-lime-accent-2",
  "bg-lime-accent-3",
  "bg-lime-accent-4",
  "bg-yellow",
  "bg-yellow-lighten-5",
  "bg-yellow-lighten-4",
  "bg-yellow-lighten-3",
  "bg-yellow-lighten-2",
  "bg-yellow-lighten-1",
  "bg-yellow-darken-1",
  "bg-yellow-darken-2",
  "bg-yellow-darken-3",
  "bg-yellow-darken-4",
  "bg-yellow-accent-1",
  "bg-yellow-accent-2",
  "bg-yellow-accent-3",
  "bg-yellow-accent-4",
  "bg-amber",
  "bg-amber-lighten-5",
  "bg-amber-lighten-4",
  "bg-amber-lighten-3",
  "bg-amber-lighten-2",
  "bg-amber-lighten-1",
  "bg-amber-darken-1",
  "bg-amber-darken-2",
  "bg-amber-darken-3",
  "bg-amber-darken-4",
  "bg-amber-accent-1",
  "bg-amber-accent-2",
  "bg-amber-accent-3",
  "bg-amber-accent-4",
  "bg-orange",
  "bg-orange-lighten-5",
  "bg-orange-lighten-4",
  "bg-orange-lighten-3",
  "bg-orange-lighten-2",
  "bg-orange-lighten-1",
  "bg-orange-darken-1",
  "bg-orange-darken-2",
  "bg-orange-darken-3",
  "bg-orange-darken-4",
  "bg-orange-accent-1",
  "bg-orange-accent-2",
  "bg-orange-accent-3",
  "bg-orange-accent-4",
  "bg-deep-orange",
  "bg-deep-orange-lighten-5",
  "bg-deep-orange-lighten-4",
  "bg-deep-orange-lighten-3",
  "bg-deep-orange-lighten-2",
  "bg-deep-orange-lighten-1",
  "bg-deep-orange-darken-1",
  "bg-deep-orange-darken-2",
  "bg-deep-orange-darken-3",
  "bg-deep-orange-darken-4",
  "bg-deep-orange-accent-1",
  "bg-deep-orange-accent-2",
  "bg-deep-orange-accent-3",
  "bg-deep-orange-accent-4",
  "bg-brown",
  "bg-brown-lighten-5",
  "bg-brown-lighten-4",
  "bg-brown-lighten-3",
  "bg-brown-lighten-2",
  "bg-brown-lighten-1",
  "bg-brown-darken-1",
  "bg-brown-darken-2",
  "bg-brown-darken-3",
  "bg-brown-darken-4",
  "bg-blue-grey",
  "bg-blue-grey-lighten-5",
  "bg-blue-grey-lighten-4",
  "bg-blue-grey-lighten-3",
  "bg-blue-grey-lighten-2",
  "bg-blue-grey-lighten-1",
  "bg-blue-grey-darken-1",
  "bg-blue-grey-darken-2",
  "bg-blue-grey-darken-3",
  "bg-blue-grey-darken-4",
];

const stamps = [
  {
    name: "Stamp 1",
    url: "/loyalty/stamps/stamp1.png",
  },
  {
    name: "Stamp 2",
    url: "/loyalty/stamps/stamp2.png",
  },
];

const baseColors = [
  "red",
  "red-lighten-5",
  "red-lighten-4",
  "red-lighten-3",
  "red-lighten-2",
  "red-lighten-1",
  "red-darken-1",
  "red-darken-2",
  "red-darken-3",
  "red-darken-4",
  "red-accent-1",
  "red-accent-2",
  "red-accent-3",
  "red-accent-4",
  "pink",
  "pink-lighten-5",
  "pink-lighten-4",
  "pink-lighten-3",
  "pink-lighten-2",
  "pink-lighten-1",
  "pink-darken-1",
  "pink-darken-2",
  "pink-darken-3",
  "pink-darken-4",
  "pink-accent-1",
  "pink-accent-2",
  "pink-accent-3",
  "pink-accent-4",
  "purple",
  "purple-lighten-5",
  "purple-lighten-4",
  "purple-lighten-3",
  "purple-lighten-2",
  "purple-lighten-1",
  "purple-darken-1",
  "purple-darken-2",
  "purple-darken-3",
  "purple-darken-4",
  "purple-accent-1",
  "purple-accent-2",
  "purple-accent-3",
  "purple-accent-4",
  "deep-purple",
  "deep-purple-lighten-5",
  "deep-purple-lighten-4",
  "deep-purple-lighten-3",
  "deep-purple-lighten-2",
  "deep-purple-lighten-1",
  "deep-purple-darken-1",
  "deep-purple-darken-2",
  "deep-purple-darken-3",
  "deep-purple-darken-4",
  "deep-purple-accent-1",
  "deep-purple-accent-2",
  "deep-purple-accent-3",
  "deep-purple-accent-4",
  "indigo",
  "indigo-lighten-5",
  "indigo-lighten-4",
  "indigo-lighten-3",
  "indigo-lighten-2",
  "indigo-lighten-1",
  "indigo-darken-1",
  "indigo-darken-2",
  "indigo-darken-3",
  "indigo-darken-4",
  "indigo-accent-1",
  "indigo-accent-2",
  "indigo-accent-3",
  "indigo-accent-4",
  "blue",
  "blue-lighten-5",
  "blue-lighten-4",
  "blue-lighten-3",
  "blue-lighten-2",
  "blue-lighten-1",
  "blue-darken-1",
  "blue-darken-2",
  "blue-darken-3",
  "blue-darken-4",
  "blue-accent-1",
  "blue-accent-2",
  "blue-accent-3",
  "blue-accent-4",
  "light-blue",
  "light-blue-lighten-5",
  "light-blue-lighten-4",
  "light-blue-lighten-3",
  "light-blue-lighten-2",
  "light-blue-lighten-1",
  "light-blue-darken-1",
  "light-blue-darken-2",
  "light-blue-darken-3",
  "light-blue-darken-4",
  "light-blue-accent-1",
  "light-blue-accent-2",
  "light-blue-accent-3",
  "light-blue-accent-4",
  "cyan",
  "cyan-lighten-5",
  "cyan-lighten-4",
  "cyan-lighten-3",
  "cyan-lighten-2",
  "cyan-lighten-1",
  "cyan-darken-1",
  "cyan-darken-2",
  "cyan-darken-3",
  "cyan-darken-4",
  "cyan-accent-1",
  "cyan-accent-2",
  "cyan-accent-3",
  "cyan-accent-4",
  "teal",
  "teal-lighten-5",
  "teal-lighten-4",
  "teal-lighten-3",
  "teal-lighten-2",
  "teal-lighten-1",
  "teal-darken-1",
  "teal-darken-2",
  "teal-darken-3",
  "teal-darken-4",
  "teal-accent-1",
  "teal-accent-2",
  "teal-accent-3",
  "teal-accent-4",
  "green",
  "green-lighten-5",
  "green-lighten-4",
  "green-lighten-3",
  "green-lighten-2",
  "green-lighten-1",
  "green-darken-1",
  "green-darken-2",
  "green-darken-3",
  "green-darken-4",
  "green-accent-1",
  "green-accent-2",
  "green-accent-3",
  "green-accent-4",
  "light-green",
  "light-green-lighten-5",
  "light-green-lighten-4",
  "light-green-lighten-3",
  "light-green-lighten-2",
  "light-green-lighten-1",
  "light-green-darken-1",
  "light-green-darken-2",
  "light-green-darken-3",
  "light-green-darken-4",
  "light-green-accent-1",
  "light-green-accent-2",
  "light-green-accent-3",
  "light-green-accent-4",
  "lime",
  "lime-lighten-5",
  "lime-lighten-4",
  "lime-lighten-3",
  "lime-lighten-2",
  "lime-lighten-1",
  "lime-darken-1",
  "lime-darken-2",
  "lime-darken-3",
  "lime-darken-4",
  "lime-accent-1",
  "lime-accent-2",
  "lime-accent-3",
  "lime-accent-4",
  "yellow",
  "yellow-lighten-5",
  "yellow-lighten-4",
  "yellow-lighten-3",
  "yellow-lighten-2",
  "yellow-lighten-1",
  "yellow-darken-1",
  "yellow-darken-2",
  "yellow-darken-3",
  "yellow-darken-4",
  "yellow-accent-1",
  "yellow-accent-2",
  "yellow-accent-3",
  "yellow-accent-4",
  "amber",
  "amber-lighten-5",
  "amber-lighten-4",
  "amber-lighten-3",
  "amber-lighten-2",
  "amber-lighten-1",
  "amber-darken-1",
  "amber-darken-2",
  "amber-darken-3",
  "amber-darken-4",
  "amber-accent-1",
  "amber-accent-2",
  "amber-accent-3",
  "amber-accent-4",
  "orange",
  "orange-lighten-5",
  "orange-lighten-4",
  "orange-lighten-3",
  "orange-lighten-2",
  "orange-lighten-1",
  "orange-darken-1",
  "orange-darken-2",
  "orange-darken-3",
  "orange-darken-4",
  "orange-accent-1",
  "orange-accent-2",
  "orange-accent-3",
  "orange-accent-4",
  "deep-orange",
  "deep-orange-lighten-5",
  "deep-orange-lighten-4",
  "deep-orange-lighten-3",
  "deep-orange-lighten-2",
  "deep-orange-lighten-1",
  "deep-orange-darken-1",
  "deep-orange-darken-2",
  "deep-orange-darken-3",
  "deep-orange-darken-4",
  "deep-orange-accent-1",
  "deep-orange-accent-2",
  "deep-orange-accent-3",
  "deep-orange-accent-4",
  "brown",
  "brown-lighten-5",
  "brown-lighten-4",
  "brown-lighten-3",
  "brown-lighten-2",
  "brown-lighten-1",
  "brown-darken-1",
  "brown-darken-2",
  "brown-darken-3",
  "brown-darken-4",
  "blue-grey",
  "blue-grey-lighten-5",
  "blue-grey-lighten-4",
  "blue-grey-lighten-3",
  "blue-grey-lighten-2",
  "blue-grey-lighten-1",
  "blue-grey-darken-1",
  "blue-grey-darken-2",
  "blue-grey-darken-3",
  "blue-grey-darken-4",
];

export default {
  getTemplates() {
    return templates;
  },
  getFields() {
    return fields;
  },
  getFieldByKey(key) {
    return fields.find((f) => f?.key === key);
  },
  getTextColors() {
    return textColors;
  },
  getBackgroundColors() {
    return backgroundColors;
  },
  getBaseColors() {
    return baseColors;
  },
  getStamps() {
    return stamps;
  },
  getCurrencies() {
    return currencies;
  },
};
